baseurl = "dmashuda.github.io"
languageCode = "en-us"
title = "Daniel Mashuda"
theme = "HugoMDL"
MetaDataFormat = "yaml"
[permalinks]
	page = "/:title/"
	about = "/:filename/"
[params]
    name = "Daniel Mashuda"
    description = "" #meta description
		background = "/images/background.jpg"
    image = "/images/avatar.jpg" #for frontpage profile card
    website = "danmashuda.com"
    email = "dmashuda@ycp.edu"
    github = "https://github.com/dmashuda/"
    copyrightyear = "2015"
    frontpageposts = 6 #number of post cards to display on frontpage
