baseurl = "http://danmashuda.com"
languageCode = "en-us"
title = "Daniel Mashuda"
theme = "material-design"
MetaDataFormat = "yaml"

[params]
    name = "Daniel Mashuda"
    description = "Thoughts of a Software Engineer" #meta description
		background = "/images/background.jpg"
    image = "/images/avatar.jpg" #for frontpage profile card
    website = "danmashuda.com"
    email = "dmashuda@ycp.edu"
    github = "dmashuda"
		linkedin = "daniel-mashuda-6b857224"
    copyrightyear = "2015"
    frontpageposts = 6 #number of post cards to display on frontpage

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
