

theme = "material-design"
languageCode = "en-us"
title = "Daniel Mashuda"
copyright = "Daniel Mashuda © 2015 "
baseurl = "dmashuda.github.io"
canonifyurls =  true

contentdir = "content"
layoutdir =  "layouts"
publishdir =  "public"

[params]
  description = " I enjoy learning about programming languages, technologies, and design paradigms. I believe that a good Software Engineer knows the strengths/weaknesses of the these things and picks the right tools for the job. When the only thing that you have is a hammer, everything looks like a nail." # optional
  github = "dmashuda" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
